#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $TALENTED_REPO == "talentedbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $TALENTED_REPO == "talentedbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $TALENTED_REPO =~ $regex ]]
    then
        if [[ $TALENTED_REPO_BRANCH ]]
        then
            echo "${TALENTED_REPO}/archive/${TALENTED_REPO_BRANCH}.zip"
        else
            echo "${TALENTED_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="mytalentedbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    TALENTEDPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $TALENTEDPATH
    echo "  • Starting talented Bot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m talentedbot
}

start_bot
